### ISSUE TITLE
(Question) Why is DirectX 12 support not merged in this repo?

### ISSUE THREAD

**Issue by AryToNeX** [sm64pc/sm64ex#129]
As the title says; sm64 already had a binary compiled against d3d12, but sources for that one are not really updated (it seems). Why don't you guys include D3D12 in this repo and make it so it's accessible under a make flag?

**Comment by fgsfdsfgs** [comment]
Then people will start asking us to actually keep it working. And I don't even have a DX12-capable setup to test it.

**Comment by AryToNeX** [comment]
Seems fair enough tbh

**Comment by coltongit** [comment]
I have a DX12 setup (Win10) I could test DX12 with. Wouldn't take much to add renderer options to the options menu for if the user's making a Windows build.

**Comment by Tikilou** [comment]
OpenGL work everywhere and it's open-source. Not DX12. (Could eventually be possible to reuse dxvk+vkd3d for Vulkan compatibility, for a Vulkan support.)
That's exactly why most of people prefer support OpenGL. (Or Vulkan, has an alternative to DX12)

**Comment by coltongit** [comment]
I'll see what I can do to get DX12 added as a viable rendering option. At least then we'll properly quash this issue.

**Comment by Leon422** [comment]
> 
> 
> I'll see what I can do to get DX12 added as a viable rendering option. At least then we'll properly quash this issue.

The only reason I can see to support DX12 is that then people could implement RTX ray tracing if they want. But Vulkan is [getting RTX support soon too](https://developer.nvidia.com/vulkan-driver) so that single advantage of DX12 will soon be gone.

So I have to ask this question: Why bother when DX12 when Vulkan exists?

**Comment by Emill** [comment]
Because DX12 is used in combination with DXGI, which provides a lot of access to vsync timing and functions to get stable latency. The flip model also gives the lowest latency.

Vulkan does not provide any such things at all unfortunately. Vulkan seems to only be designed for "max fps" games currently.

**Comment by Tikilou** [comment]
> Because DX12 is used in combination with DXGI, which provides a lot of access to vsync timing and functions to get stable latency. The flip model also gives the lowest latency.
> 
> Vulkan does not provide any such things at all unfortunately. Vulkan seems to only be designed for "max fps" games currently.

Well, we should found an other way to do that so. DX12 is only one platform compatible, it's loss of time and energy. It will be more benefit for everyone to working only on portable/multi-platform feature. We don't need a situation where we gonna have mods/patchs/improvenants of source code only compatible Dx12 and break compatibility for others.

**Comment by Emill** [comment]
Thankfully most things are abstracted away so if you want to modify some rendering stuff you often only need to touch gfx_pc.c (or the game itself) and not so often the opengl/dx12 specific code.

**Comment by vrmiguel** [comment]
Closed by inactivity. Reopen if necessary.

**Comment by coltongit** [comment]
fgsfds is working on implementing this as well as the d3d11 renderer into the repo as we speak.

**Comment by vrmiguel** [comment]
Closing since D3D11 and D3D12 renderers are now available again.
