### ISSUE TITLE
Feature Request Scipting for mods 

### ISSUE THREAD

**Issue by MissLav** [sm64pc/sm64ex#164]
Quake 3's c vm might fit well for this
https://github.com/jnz/q3vm

examples 
garrys mod uses lua
gzdoom uses decorate and zscipt

basically some sort of non engine side code that allows for accessible and stack-able modding

Anti-example
Quake2's Dll setup
requires compiling per arch horrible for long term mod support

**Comment by Tikilou** [comment]
I don't think lua is a good way. I'm using minetest game usually and it's a terrible way when you add lot of mods or big mod, performances are not good.
It will be better to add for long term to have binary precompiled modules/extension support. (Why not an archive with lua script + precompiled binaries/libraries support multiplatform ?)
It's possible to include a licence for that part wich litterally ask guys to distribute all plugins/mods open source, we can modify and redistribute.
