### ISSUE TITLE
Request: Exit

### ISSUE THREAD

**Issue by enigma9o7** [sm64pc/sm64ex#200]
I've been told windows can exit with Alt+F4.  This does not work for me on linux.  Please enable that, or ALT-X CTRL-X CTRL-Q or all of them.

Right now, if I set my mouse to control the camera, I can no longer close the app.  Before I'd just use mouse to exit.   I can't even alt-tab to other windows, etc.  

There is a kinda fix in current build, can exit from bottom of pause right-shift menu, and mouse comes back when paused too.  But can't always pause (intro/etc)...

**Comment by Leon422** [comment]
There's an "exit game" option in the options menu.

**Comment by vrmiguel** [comment]
> I've been told windows can exit with Alt+F4. This does not work for me on linux. 

Aside from the "exit game" option, Alt+F4 **does** work, at least on Linux Mint 19.2 using latest nightly, as well as Esc breaking out of fullscreen. Check if that shortcut is even set up on your distro.

**Comment by enigma9o7** [comment]
In fact, alt+f4 was previously bound to open desktop 4 by default, but I cleared that binding already.  Not sure how to test it further, tried http://en.key-test.ru/ and behaves normal there, holding down alt holds alt, every time i press F4 it shows F4.  

Esc takes it out of full screen, but irrelevant, still no mouse pointer when mouse controlling camera.

Seems like my issue is specific to my distro or something, this can be closed if it's just me.

**Comment by vrmiguel** [comment]
Try running `sudo kbd_mode -s`.

**Comment by enigma9o7** [comment]
sudo kbd_mode -s still didn't allow alt+f4 exit, but thanks for idea.

A couple recent improvements have made this less of an issue.  One is the ability to skip the into, the other is that the mouse control is returned when game is paused.   Not that I still wouldn't mind a quit exit keybinding.

**Comment by enigma9o7** [comment]
Okay, so this is a non-issue, and it's me not knowing how to use my own PC.

By default, windows uses alt-f4 to close window.  It's not the game that's taking alt-f4 to exit.   So I just bound alt-f4 to close window.  Duh.
