### ISSUE TITLE
60 fps?

### ISSUE THREAD

**Issue by uper333** [sm64pc/sm64ex#257]
Good, I just tried a compilation for nintendo switch that works at 60fps, they just implemented it and it has some textures flaws but it works very well, although I haven't tried too much, are you planning to add 60fps to this version?

Buenas, acabo de probar una compilacion para nintendo switch que funciona a 60fps, lo acaban de implementar y tiene algunos fallos de texturas pero por lo demas funciona muy bien, aunque no he probado demasiado, se tiene pensado añadir 60fps a esta version?

**Comment by Zoltar007** [comment]
@uper333 There's an open issue for this https://github.com/sm64pc/sm64pc/issues/158

**Comment by fgsfdsfgs** [comment]
There's a 60 fps patch now.
