### ISSUE TITLE
The game crashes when I'm in Rainbow Road

### ISSUE THREAD

**Issue by RafterFD** [sm64pc/sm64ex#322]
When I'm in Rainbow road, the game just Crashes and, obviously closes

I've build the game with "BETTERCAMERA" and "NODRAWINGDISTANCE"

This happen just starting the level, so I can't do anything else...

Link to Google Drive Video (I hope this link doesn't break the guidelines): https://drive.google.com/file/d/1HMZDwknBW4MfYAmpT48clCacF6W5YiYI/view?usp=sharing

SO:
W10 (64 Bits)

Link to my Save File:
[sm64_save_file.zip](https://github.com/sm64pc/sm64pc/files/4757011/sm64_save_file.zip)

**Comment by Zerocker** [comment]
Hello. I've build and tested the game with your flags plus "TEXTSAVES" - no issues found. Make sure that you build with the latest up-to-date commits on **nightly** branch

**Comment by coltongit** [comment]
This is because master has a crippling bug with the level where if you go to a certain area and FLJ, the game hangs but the music still plays. The latest nightly fixes this issue and more.

**Comment by vrmiguel** [comment]
Is this running on nightly?

**Comment by RafterFD** [comment]
I'm not sure (? I did the steps that come on this page

https://github.com/sm64pc/sm64pc/blob/nightly/README_es_ES.md

(I use the Spanish version 'cause it's my native language)
