### ISSUE TITLE
Deadzone should be made better

### ISSUE THREAD

**Issue by danielh05** [sm64pc/sm64ex#324]
I have a really shitty controller so I need to use the Deadzone setting "30" to at least be able to play without mario walking to the right on his own. The problem with this is that when you use a high deadzone you can't walk that slowly anymore and that is slightly annoying.

**Comment by GateGuy** [comment]
Well, that's what a deadzone does; it cancels out input within a certain range while leaving everything else unaffected. At the risk of sounding like "that guy", you may want to just look into using a different controller since I imagine you'd run into the same problem with any game.

**Comment by DSuarez93** [comment]
This is something you can't control with this game because it was designed for a very high range of joystick precision so you can tip-toe and fully run with the same stick without modulation. Figure out how to recalibrate your controller deadzone outside this executable, or throw out the controller and get a DS4.

**Comment by coltongit** [comment]
> This is something you can't control with this game because it was designed for a very high range of joystick precision so you can tip-toe and fully run with the same stick without modulation. Figure out how to recalibrate your controller deadzone outside this executable, or throw out the controller and get a DS4.

Agreed, as this was the case even on the original N64 version back in the day

**Comment by vrmiguel** [comment]
> Well, that's what a deadzone does; it cancels out input within a certain range while leaving everything else unaffected. At the risk of sounding like "that guy", you may want to just look into using a different controller since I imagine you'd run into the same problem with any game.

I agree. This feels like a problem with your controller rather than the current deadzone configuration. If you're on Windows, have you tried running the game under the Steam? Steam Input may help you out here.
