### ISSUE TITLE
Tree does not face the camera properly

### ISSUE THREAD

**Issue by danielh05** [sm64pc/sm64ex#333]
When looking over a tree in sm64, the tree faces towards the camera fully,
in the PC Port it doesn't.
Examples:
Real SM64 (Running on actual hardware):
https://i.imgur.com/7U6cY32.png
PC Port:
https://i.imgur.com/AfvBi1O.png

**Comment by fgsfdsfgs** [comment]
That was actually specifically added in a pull request because billboarding trees look weird when freelook is enabled. I guess we should probably make it an option.

**Comment by danielh05** [comment]
That does make sense for a freelook camera. Maybe a check for looking if freelook is on or off can do the trick.
