### ISSUE TITLE
Unable to Access Cheat Menu by pressing L3

### ISSUE THREAD

**Issue by jvhellraiser** [sm64pc/sm64ex#352]
Really simple enter the game , Pause press L3 times......

Nothing Happens. i could use --cheats but
i find it stupid using --cheats when we had before 
a simple way of accessing the cheat menu just by pressing L3.

**Comment by fgsfdsfgs** [comment]
L **three times**, not **L3 times**. And that means the N64 L, which is bound to Left Shift or L Shoulder by default.

**Comment by jvhellraiser** [comment]
Is funny cause  i have a pro controller and by pressing L it was not working at the moment, i had to remap once again to L trigger. anyway sorry for bothering.

**Comment by fgsfdsfgs** [comment]
I admit, it is counter intuitive. Probably should clarify it in the instructions more.
