### ISSUE TITLE
Options menu doesn't open

### ISSUE THREAD

**Issue by Ka1eb** [sm64pc/sm64ex#354]
When I go into the start menu, hitting R doesn't do anything. No extra options pop up. I've compiled the game twice now with the same issue both times. I used the build options BETTERCAMERA=1, EXT_OPTIONS_MENU=1 and DISCORDRPC=1. Am I doing something wrong?

**Comment by fgsfdsfgs** [comment]
Which R are you hitting? It has to be the N64 R, which is bound to Right Shift on the keyboard and R on your controller.

**Comment by Ka1eb** [comment]
Oh, I was thinking it was the letter R on the keyboard. I just tried it and Right Shift opened the menu.  Sorry about that, I just completely forgot there was an "R" button on an N64 controller.
