### ISSUE TITLE
Free camera stops working after loading levels

### ISSUE THREAD

**Issue by RiskyJumps** [sm64pc/sm64ex#356]
Version: 52e32ba Linux x86_64

The game starts with free camera disabled despite it being enabled in the config file / game options. Every time a level gets loaded it returns to being disabled; it still reads "Enabled", though.

**To Reproduce**
1. Make sure you have `bettercam_enable true` and `bettercam_mouse_look true` in the config file
2. Start the game and move your mouse, it won't work.
3. Go to "Options" menu, disable "Free Camera" and exit "Options" menu (you must exit)
4. Go to "Options" menu, enable "Free Camera" and exit "Options" menu
6. Move your mouse, it will work now.
7. Enter the castle (or any level, really)
8. Move your mouse, it won't work again

**Notes**
- Every time you go to any level you need to repeat steps 3 and 4.
- Toggling either "Mouse Look" or "Analog Camera" exiting "Options" and toggling them again does nothing.
- The keyboard camera will be the vanilla one when the mouse is not working.

**Expected behavior**
Free Camera must work from the start if enabled in the config file / game options and shouldn't stop working after loading levels.

**Comment by fgsfdsfgs** [comment]
Check if the problem has been fixed with cb9bd73.

**Comment by RiskyJumps** [comment]
It works, thank you.
