### ISSUE TITLE
"strdup" undefined in old Mingw.org with nightly

### ISSUE THREAD

**Issue by yksoft1** [sm64pc/sm64ex#357]
> make[1]: Entering directory `/c/temp/smpc/tools/audiofile'
> g++ -std=c++11 -DNDEBUG -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -O2 -I. -c audiofile.cpp
> audiofile.cpp: In function 'status _afOpenFile(int, File*, const char*, _AFfilehandle**, AFfilesetup)':
> audiofile.cpp:14640:28: error: 'strdup' was not declared in this scope
>    filehandle->m_fileName = strdup(filename);
>                             ^~~~~~
> audiofile.cpp:14640:28: note: suggested alternative: 'strcmp'
>    filehandle->m_fileName = strdup(filename);
>                             ^~~~~~
>                             strcmp
> Makefile:7: recipe for target `audiofile.o' failed
> make[1]: *** [audiofile.o] Error 1
> make[1]: Leaving directory `/c/temp/smpc/tools/audiofile'
> Makefile:41: recipe for target `audiofile/libaudiofile.a' failed
> make: *** [audiofile/libaudiofile.a] Error 2
> make: Leaving directory `/c/temp/smpc/tools'
> Makefile:242: *** Failed to build tools.  Stop.

I think strdup is defined in MSVCRT as _strdup. 
It's a POSIX-only function I think. mingw-w64 has that implemented, but MinGW.org does not have it.

EDIT: changed --std=c++11 to --std=gnu++11 in tools/audiofile/Makefile then the building worked.

**Comment by coltongit** [comment]
that'd be an easy PR to make a fix for. should work on top of #93
