### ISSUE TITLE
Game does not compile with "BETTERCAMERA=1"

### ISSUE THREAD

**Issue by danielh05** [sm64pc/sm64ex#359]
I'm using nightly with a US version of the game.
Stops building around here:
VOID_UB -DF3DEX_GBI_2E -fno-strict-aliasing -fwrapv -DBETTERCAMERA -DEXT_OPTIONS_MENU -o build/us_pc/src/pc/audio/audio_sdl.o src/pc/audio/audio_sdl.c
src/pc/gfx/gfx_pc.c: In function 'import_texture_rgba32':
src/pc/gfx/gfx_pc.c:339:54: warning: passing argument 1 of 'gfx_rapi->upload_texture' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  339 |     gfx_rapi->upload_texture(rdp.loaded_texture[tile].addr, width, height);
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
src/pc/gfx/gfx_pc.c:339:54: note: expected 'uint8_t *' {aka 'unsigned char *'} but argument is of type 'const uint8_t *' {aka 'const unsigned char *'}

**Comment by fgsfdsfgs** [comment]
That's not an error. Post the entire log please.

**Comment by danielh05** [comment]
Oh sorry, my bad. Could you tell me where the logs are located at? I copied that from my msys.

**Comment by fgsfdsfgs** [comment]
Just copy the entire thing from your msys window and put it on like dpaste.com or in a text file and post it here.
Or find the line that actually says `error`.

**Comment by danielh05** [comment]
Oh god I made a huge mistake here, the error was coming from an older line of code that I wrote a while back that I completely forgot about and that was causing errors with the better camera setting. So sorry for wasting your time with this, I feel really bad.

**Comment by fgsfdsfgs** [comment]
It's alright.
