### ISSUE TITLE
peach/geo_header.h and koopa_shell/geo_header.h don't exist....

### ISSUE THREAD

**Issue by ApacheThunder** [sm64pc/sm64ex#362]
I'm not sure where these files are supposed to get generated but they break compilation currently due to them not existing at the time of compile. I get compile errors with actors/group10.h and actors/common.h due to peach/geo_header.h and koopa_shell/geo_header.h not existing.

This could be an issue on sm64pcBuilder 2's side? But I'm not sure. This compiled fine for me from the last version of sm64pcBuilder 2 (version 1.0.4) but then broke with 1.0.5. 

Commenting out these include references makes compile succeed. Game seems to have no issue displaying the koopa shell (have not tested Peach as I'd have to beat final Bowser fight to see that one) so the include statement seems no longer needed?

If these files have been deprecated. I'd recommend removing these include statements to prevent future compile issues.

**Comment by fgsfdsfgs** [comment]
I can compile the source in this repo just fine using `make`, so check with the dev of sm64builder. Check what patches you are using, some of them are not compatible with nightly.

**Comment by ApacheThunder** [comment]
Interesting. Must be a bug with the builder or a change made in the HD models. I've used these HD models in the past version of sm64builder just prior to the latest available build so I don't think it's a incompatibility. But I'll redownload the repo and have the builder do a version without these hd models to see if the issue persists.
