### ISSUE TITLE
Repository renamed?

### ISSUE THREAD

**Issue by superbonaci** [sm64pc/sm64ex#367]
Want to know if the repository was renamed from `sm64pc` to `sm64pc/sm64ex`. If that was made what was the reason?

**Comment by fgsfdsfgs** [comment]
It was renamed. This is based on old leaked source code of the original PC port. As it went public recently as [sm64-port](https://github.com/sm64-port/sm64-port), the name was changed to avoid confusion and to make the status of this as a fork more clear.

**Comment by superbonaci** [comment]
Ok, so if I do a `git  pull` on old folder do I have to rename it?

**Comment by fgsfdsfgs** [comment]
No. Github redirects from the old address.

**Comment by superbonaci** [comment]
Ok but if I do a new `git clone https://github.com/sm64pc/sm64ex.git` the folder would be different right?

**Comment by fgsfdsfgs** [comment]
Yes, by default. However if for some reason you really need it to be named `sm64pc` you can do this
```git clone https://github.com/sm64pc/sm64ex.git sm64pc```

**Comment by superbonaci** [comment]
Great, thanks. I just renamed the folder from `sm64pc` to `sm64ex` so I preserve all the data.
