### ISSUE TITLE
Camera bugs when using flying cap with BETTERCAMERA=1

### ISSUE THREAD

**Issue by BrianAllred** [sm64pc/sm64ex#370]
**Describe the bug**
Camera doesn't follow Mario closely enough while using the flying cap. This causes Mario to slowly drift further and further away from the camera until he lands. Also, camera doesn't start in the correct position in the Flying Cap stage.

**To Reproduce**
1. Build with `BETTERCAMERA=1`
2. Fly with flying cap.

**Expected behavior**
Camera behaves normally (with respect to game and specified `BETTERCAMERA` options).

**Screenshots**
https://imgur.com/a/UL6VySj

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Additional context**
Building with `BETTERCAMERA=0` fixes the issue.

**Comment by fosspill** [comment]
Can confirm this on Windows as well, makes flying cap extremely hard to use.

**Comment by enigma9o7** [comment]
Tried to replicate, figured out it only happens is the freecamera is disabled in settings.

**Comment by ineedhelpbad** [comment]
I fixed this by changing line 1756 in sm64ex/src/game/mario_actions_airborne.c from
    "set_camera_mode(m->area->camera, m->area->camera->defMode, 1);"
to
    "set_camera_mode(m->area->camera, CAMERA_MODE_BEHIND_MARIO, 1);"
I'm new to github so I'm not sure how to submit changes.
