### ISSUE TITLE
Longer input delay

### ISSUE THREAD

**Issue by fortofawesome35** [sm64pc/sm64ex#371]
The new pcbuilder2 nightly update seems to have made the input delay between button presses longer. It is a bit more difficult to do actions such as triple jumps and punches because of it. The previous update had faster input delay, so such actions that require timing were rather easy to do. Can you figure out why that is?

**Comment by fgsfdsfgs** [comment]
I personally don't notice it, but you can try either enabling vsync in the display options (don't forget to press Apply after that), or using the DX11 renderer. The recent vsync-related update might have reset your vsync setting to Disabled, and when it's off it uses a crappy timer-based framerate limiter, which might cause input lag.
