### ISSUE TITLE
nightly fails to build on OSX

### ISSUE THREAD

**Issue by BrianAllred** [sm64pc/sm64ex#372]
Building with `gmake VERSION=us OSX_BUILD=1` and I get

```
n64graphics_ci_dir/exoquant/exoquant.c:28:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
```

master builds fine.

**Comment by sarezjay** [comment]
If you haven't fixed this yet, the solution is to go into that file (exoquant.c) and comment out the include for malloc.h

**Comment by coltongit** [comment]
> If you haven't fixed this yet, the solution is to go into that file (exoquant.c) and comment out the include for malloc.h

try using the OSX build flag in the makefile and put malloc behind an ifndef there

**Comment by rawr51919** [comment]
This tweak (via an ifdef) has been in nightly for a while now. See if nightly fixes your build issue now @BrianAllred
