### ISSUE TITLE
Web compiling Help

### ISSUE THREAD

**Issue by meowmeoe** [sm64pc/sm64ex#374]
I'm a bit of a noob with this kind of stuff.  I've already made the Windows version but would like to also make the web one, just to try it out.

I'm doing this through MSYS on a Windows x64 computer.
I already have Emscripten installed (I can go in the emsdk directory).
I have sm64ex-master, and I have a "baserom.us.z64" inside it. (I already used it for sm64pc and sm64ex(Windows))

Can anybody give me some step by step instructions for what to do next?  I'm not really sure where I need to be to run "make TARGET_WEB=1".

**Comment by BrianAllred** [comment]
I'm curious to know the answer to this. I got a "successful" build, but it didn't run correctly. I had to build the web version on Linux for it to work.

**Comment by meowmeoe** [comment]
Were you using MSYS on Windows?  Because theoretically that should work the same way as Linux.

**Comment by BrianAllred** [comment]
Yeah. I followed the instructions for installing emscripten on Windows, and then inside MSYS2's MinGW64 prompt, I did `source emsdk_env.sh` before building.

**Comment by meowmeoe** [comment]
Where do I/did you run "make TARGET_WEB=1"?  I tried in sm64ex-master/tools and got errors for the audiofile...

**Comment by BrianAllred** [comment]
In the main sm64ex folder. And I don't know if it makes a difference, but I was on the nightly branch.

**Comment by meowmeoe** [comment]
I just tried the nightly and got the same thing:

----- MSYS /e/----/-------/--------/sm64ex/sm64ex-master
$ make TARGET_WEB=1
fatal: not a git repository (or any of the parent directories): .git
make: gcc: No such file or directory
make: *** [Makefile:74: n64graphics] Error 127
Traceback (most recent call last):
  File "./extract_assets.py", line 282, in <module>
    main()
  File "./extract_assets.py", line 157, in main
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-s', '-C', 'tools/', 'n64graphics', 'skyconv', 'mio0', 'aifc_decode']' returned non-zero exit status 2.
Makefile:247: *** Failed to extract assets.  Stop.

Maybe I should just boot Linux off a usb drive and try from there?  Not sure if it's really worth that much effort.

**Comment by BrianAllred** [comment]
It says it can't find gcc, did you install all the right dependencies?

From the wiki: `pacman -S mingw-w64-i686-glew mingw-w64-x86_64-glew mingw-w64-i686-SDL2 mingw-w64-x86_64-SDL2 python3`

**Comment by meowmeoe** [comment]
I managed to get MSYS running.  It extracted a bunch of stuff, and I now have a "sm64ex-master/build/us_web", but it might be incomplete?  The only file there aside from folders is "level_rules.mk".

**Comment by BrianAllred** [comment]
Run the build again (or delete the build folder). Sometimes the build doesn't finish depending on the state of the build folder

**Comment by meowmeoe** [comment]
Take 2:

Welp...

$ make TARGET_WEB=1
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
make: Entering directory '/e/Play/Folders/PC Games/sm64ex/sm64ex-master/tools'
make: Nothing to be done for 'all'.
make: Leaving directory '/e/Play/Folders/PC Games/sm64ex/sm64ex-master/tools'
cpp -P -DVERSION_US -DNON_MATCHING -DAVOID_UB -DTARGET_WEB -DUSE_GLES -I . -o build/us_web/level_rules.mk levels/level_rules.mk
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
make: Entering directory '/e/Play/Folders/PC Games/sm64ex/sm64ex-master/tools'
make: Nothing to be done for 'all'.
make: Leaving directory '/e/Play/Folders/PC Games/sm64ex/sm64ex-master/tools'
/bin/sh: emcc: command not found
make: *** [Makefile:1034: build/us_web/src/engine/behavior_script.o] Error 127

Not sure if this is still worth it.  This was after deleting the build folder and doing the exact same steps as the first time.

**Comment by BrianAllred** [comment]
Are you using git to clone the repo or just downloading a snapshot? Use git to clone the repo: `git clone https://github.com/sm64pc/sm64ex.git`, then enter the repo and switch branches with `cd sm64ex && git checkout nightly`

And then it says emcc isn't found. Did you `source emsdk_env.sh`, wherever you setup emsdk?

**Comment by meowmeoe** [comment]
I'm pretty sure I did, because that was on the Emscripten install guide.  Is there a way to check?

**Comment by BrianAllred** [comment]
Well, the install guide for Windows is assuming you're building using Windows tools. You probably executed `.\emsdk_env.bat` if you followed the guide, which won't work for MSYS builds. You have to execute `source emsdk_env.sh` from inside the MSYS prompt when building with MSYS. 

So, what I did was

In a regular command prompt window:
- `git clone https://github.com/emscripten-core/emsdk.git`
- `cd emsdk`
- `.\emsdk install latest`
- `.\emsdk activate latest`

Then in an MSYS MinGW64 prompt:
- Enter the emsdk directory
- `source emsdk_env.sh`

**Comment by BrianAllred** [comment]
Also, feel free to come by the Discord, there's a couple of help desk channels there, you'd get more help than just me, haha.

**Comment by meowmeoe** [comment]
I think ima go over there and restart in a few hours...  Thanks for the help!

**Comment by meowmeoe** [comment]
Is there a link to the Discord here?

**Comment by BrianAllred** [comment]
https://discord.gg/2Gb7aK
