### ISSUE TITLE
Save state New feature request.

### ISSUE THREAD

**Issue by impeeza** [sm64pc/sm64ex#388]
It will be nice add to the PC port a "Save State/Restore State" feature some times is hard return where you had to left the game.

I know is no a "purist" feature, but it can be implemented not enabled by default. I could be toggle on options menu.

**Comment by ThiagoDreyar** [comment]
good idea

**Comment by impeeza** [comment]
No advances?

**Comment by impeeza** [comment]
Sorry the repo is stalled, it's a great work
