### ISSUE TITLE
Text Saves aren't saving cannon flags.

### ISSUE THREAD

**Issue by DarkRTA** [sm64pc/sm64ex#397]
**Describe the bug**
When opening a cannon in any course when using text saves, the flag for it is never saved resulting in cannons being closed when reloading the save file.

Steps to reproduce:
1. Go to any course with a cannon.
2. Open said cannon.
3. Reload the save.
4. Cannon should be closed.

**Comment by VDavid003** [comment]
The issue seems to be caused by save_file_get_star_flags cutting off the cannon flag bit, and the text saves code never actually saving it anywhere else.
