### ISSUE TITLE
Won't compile on Windows 10

### ISSUE THREAD

**Issue by Doriphor** [sm64pc/sm64ex#398]
**Describe the bug**
I can't for the life of me get this to compile on MSYS2. I followed the wiki's instructions perfectly (including the MSYS2 setup guide) but it always messes up with:
``gcc -c -O2 -m64 -I include -I build/us_pc -I build/us_pc/include -I src -I . -DRAPI_GL=1 -DWAPI_SDL2=1 -DAAPI_SDL2=1 -DCAPI_SDL2=1 -DHAVE_SDL2=1 `sdl2-config --cflags` -DVERSION_US -DNON_MATCHING -DAVOID_UB -DF3DEX_GBI_2E -fno-strict-aliasing -fwrapv -DBETTERCAMERA -DTEXTSAVES -DTEXTURE_FIX -DEXT_OPTIONS_MENU -o build/us_pc/src/pc/pc_main.o src/pc/pc_main.c``
`src/pc/platform.c:85:10: fatal error: SDL2/SDL.h: No such file or directory`
`   85 | #include <SDL2/SDL.h>`
`      |          ^~~~~~~~~~~~`
`compilation terminated.`
`make: *** [Makefile:1034: build/us_pc/src/pc/platform.o] Error 1`

**To Reproduce**
1. Follow the compilation instructions on Windows 10 (with Mingw64)

**Additional context**
The same problem arises with the nightly sources. I tried compiling on Linux and it works just fine.

And yes, SDL2 is installed in MSYS2 and I updated the path in Windows and the .ini file for Mingw64

**Comment by fgsfdsfgs** [comment]
Which SDL2 package did you install?
You have to run all of this from the MINGW64 prompt and the package has to be `mingw-w64-x86_64-SDL2`.

**Comment by Doriphor** [comment]
I did a copy paste of the wiki instructions:

``pacman -S mingw-w64-i686-glew mingw-w64-x86_64-glew mingw-w64-i686-SDL2 mingw-w64-x86_64-SDL2 python3``

And I'm running it from the MINGW64 prompt, yes.

**Comment by fgsfdsfgs** [comment]
But did all of that crap actually install?
Run `ls -la /mingw64/include/SDL2` and tell me if it says "file not found" or something along those lines.

**Comment by Doriphor** [comment]
``dorip@DESKTOP-6OINQKD MINGW64 ~/sm64ex-master``
``$ ls -la /mingw64/include/SDL2``
``total 1945``

**Comment by fgsfdsfgs** [comment]
I dunno, multiple people have built this on Windows 10 before without issue.
What exactly did you change in the ini files and the PATH variable?
Also, have you tried building nightly?

**Comment by Doriphor** [comment]
I tried building nightly with the same outcome.

I changed mingw64.ini by uncommenting MSYS2_PATH_TYPE=inherit as the wiki suggests in its MSYS2 installation guide. (I also tried this all before doing this with the same outcome)

For the PATH variable, I added C:\msys64\mingw64\bin and C:\msys64\mingw32\bin in that order as the guide suggests. After the SDL2 issue I mention in this post, I also tried to add C:\msys64\mingw64\include and C:\msys64\mingw32\include, just in case, but it didn't change anything.

I also tried this all in a completely fresh Windows 10 VM with the same outcome.

**Comment by fgsfdsfgs** [comment]
What is happening is somehow `/mingw64/include` isn't in the include path, even though it should be there by default when you run the MINGW64 prompt and it is for me and a lot of other people.
What's the output of `which gcc`?

**Comment by Doriphor** [comment]
For some reason it shows it as being `/usr/bin/gcc` (on both my PC and the fresh VM)

**Comment by Doriphor** [comment]
After doing `pacman -S mingw64/mingw-w64-x86_64-gcc` it now shows it as being `/mingw64/bin/gcc` and I can compile the project now! I guess the guide was incomplete but would work for most people because they'd install it themselves beforehand?

**Comment by fgsfdsfgs** [comment]
Yeah I think by editing PATH and that INI file you did it so it inherited the GCC from the regular MSYS environment. I should add the correct GCC packages to the guide.

**Comment by Doriphor** [comment]
Alright I can confirm that the build finishes and the game runs fine. And I don't think that was it, I just think that the Mingw version of GCC was never installed in the first place and therefore it would fallback to the one in /usr/bin/gcc. Thank you for your assistance! I'm glad we could figure it out :)
