### ISSUE TITLE
Changed controls and cant change them back!

### ISSUE THREAD

**Issue by KrazyDave1930** [sm64pc/sm64ex#401]
so I accidently changed the controls in the sm64ex-nightly and I cant change them back. And all I can do is press start and move the cursor.

**Comment by fgsfdsfgs** [comment]
Nuke either the entire config or all the controls from it (the lines beginning with `key_`).
The config is in `AppData/Roaming/sm64ex`, you can access it quickly by pasting `%APPDATA%/sm64ex` into Explorer's address bar.

**Comment by KrazyDave1930** [comment]
thank you

**Comment by KrazyDave1930** [comment]
I tried what you said and it still doesn't work. all I can do is move Mario's head around in the beginning screen?

**Comment by fgsfdsfgs** [comment]
Well if you can move it around then the controls are working. Press Space.

**Comment by KrazyDave1930** [comment]
nothing

**Comment by KrazyDave1930** [comment]
I've figured it out, thanks a lt
