### ISSUE TITLE
Cannot compile with sm64pcbuilder: File missing.

### ISSUE THREAD

**Issue by LTSchmiddy** [sm64pc/sm64ex#415]
**Describe the bug**
I'm unable to build/compile the game on Windows via *sm64pcbuilder2* regardless of the settings I select.
Yes, I know the instructions say that less experienced users should use *sm64pcbuilder*. However:

* I want some of the additional features that the advanced version provides.
* I do know what I'm doing. I'm a fellow programmer, actually. I have some experience with these things.

Specifically, the error message I'm getting is as follows:
```
levels/intro/leveldata.c:3321:11: fatal error: levels/intro/blue.rgba16.inc.c: No such file or directory
 3321 |  #include "levels/intro/blue.rgba16.inc.c"
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
I checked the directory listed above. This file does not exist. Perhaps it wasn't added to the repository on accident?

* Yes, my ROM is verified.
* I did initially use *sm64pcbuilder*. That works perfectly fine.
* Yes, MSYS2 and MinGW are up-to-date.
* Yes, I tried cloning the repository again.

**To Reproduce**
... Delete the file  "levels/intro/blue.rgba16.inc.c" and try to build, I guess.

**Expected behavior**
The executable to build and run.

**Desktop (please complete the following information):**
 Windows 10

**Comment by fgsfdsfgs** [comment]
This is a sm64pcbuilder2 issue. I am not the dev of that. This repo builds just fine on my machine, manually, using msys2/mingw-w64.
However, I would guess that after applying a combination of patches (without unapplying any prior incompatible patches, as it tends to happen with the builder), your source copy got fucked up. Make sure you *actually* did re-clone the *sm64ex repo* and not the *builder repo*, assuming they have one.
I can't provide much more advice, maybe ask the builder devs, I dunno.

**Comment by rawr51919** [comment]
The only way to really fix this might be to just keep blue.rgba16.inc.c in your build directory.

**Comment by Lanzhiyii** [comment]
hello，something wrong with the sm64builder 2, could you solve it???
![Uploading v1.21.3 - sm64ex-coop-coop - US - [D__msys64] - SL - 64-bit - Win11                                                   2024_7_8 19_30_29.png…]()

**Comment by Lanzhiyii** [comment]
![Uploading v1.21.3 - sm64ex-coop-coop - US - [D__msys64] - SL - 64-bit - Win11                                                   2024_7_8 19_30_29.png…]()

**Comment by fgsfdsfgs** [comment]
That's sm64ex-coop related, please ask [here](https://github.com/coop-deluxe/sm64coopdx). Not to mention I don't develop sm64pcbuilder.
