### ISSUE TITLE
collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by GbaCretin** [sm64pc/sm64ex#416]
I tried to compile this repository, but I get these linking errors:
```
/usr/bin/ld: build/us_pc/src/pc/platform.o: in function `sys_user_path':
/run/media/gbacretin/acfc28cf-9caa-48bf-8192-2a6a0a5a4d8f/Games/sm64ex/src/pc/platform.c:90: undefined reference to `SDL_GetPrefPath'
/usr/bin/ld: build/us_pc/src/pc/platform.o: in function `sys_exe_path':
/run/media/gbacretin/acfc28cf-9caa-48bf-8192-2a6a0a5a4d8f/Games/sm64ex/src/pc/platform.c:106: undefined reference to `SDL_GetBasePath'
/usr/bin/ld: build/us_pc/src/pc/audio/audio_sdl.o: in function `audio_sdl_buffered':
/run/media/gbacretin/acfc28cf-9caa-48bf-8192-2a6a0a5a4d8f/Games/sm64ex/src/pc/audio/audio_sdl.c:31: undefined reference to `SDL_GetQueuedAudioSize'
/usr/bin/ld: build/us_pc/src/pc/audio/audio_sdl.o: in function `audio_sdl_play':
/run/media/gbacretin/acfc28cf-9caa-48bf-8192-2a6a0a5a4d8f/Games/sm64ex/src/pc/audio/audio_sdl.c:41: undefined reference to `SDL_QueueAudio'
/usr/bin/ld: build/us_pc/src/pc/controller/controller_sdl.o: in function `controller_sdl_init':
/run/media/gbacretin/acfc28cf-9caa-48bf-8192-2a6a0a5a4d8f/Games/sm64ex/src/pc/controller/controller_sdl.c:106: undefined reference to `SDL_GameControllerAddMappingsFromRW'
collect2: error: ld returned 1 exit status
make: *** [Makefile:1048: build/us_pc/sm64.us.f3dex2e] Errore 1
```

1. Follow the guide on the wiki
2. Use this command `make BETTERMOUSE=1 TEXTURE_FIX=1 TEXTURE_FIX=1 -j3` to compile the repository

What I expected to happen was the project compiling succesfully

 - OS: Manjaro Linux
 - Version: I've cloned the master branch yesterday (5th of september)

I have all needed libraries installed

**Comment by fgsfdsfgs** [comment]
It seems you are either compiling the SDL2 backends with SDL1 or you have a very outdated version of SDL2.
Can you find out the version (e.g. with `pacman -Q --info sdl2`) and post it here?

**Comment by GbaCretin** [comment]
> pacman -Q --info sdl2

The version of sdl2 is `2.0.12-2`

**Comment by fgsfdsfgs** [comment]
Post the full build log.

**Comment by GbaCretin** [comment]
> Post the full build log.
[build.log.txt](https://github.com/sm64pc/sm64ex/files/5178227/build.log.txt)

**Comment by fgsfdsfgs** [comment]
What do `sdl2-config --libs` and `sdl2-config --cflags` return?

**Comment by GbaCretin** [comment]
> What do `sdl2-config --libs` and `sdl2-config --cflags` return?

`sdl2-config --libs` returns `-L/usr/local/lib -Wl,-rpath,/usr/local/lib -lSDL2 -lpthread`,
`sdl2-config --cflags` returns `-I/usr/local/include/SDL2 -D_REENTRANT`

**Comment by fgsfdsfgs** [comment]
Can you give me a log with error messages in it as well? E. g. `make TEXTURE_FIX=1 -j3 >build.log 2>&1`

**Comment by GbaCretin** [comment]
> Can you give me a log with error messages in it as well? E. g. `make TEXTURE_FIX=1 -j3 >build.log 2>&1`

[build.log](https://github.com/sm64pc/sm64ex/files/5178246/build.log)

**Comment by fgsfdsfgs** [comment]
What about `ls -la /usr/local/lib/libSDL2*`?

**Comment by GbaCretin** [comment]
> What about `ls -la /usr/local/lib/libSDL2*`?

```
lrwxrwxrwx 1 root root      20 13 giu 21.32 /usr/local/lib/libSDL2-2.0.so.0 -> libSDL2-2.0.so.0.0.0
-rwxr-xr-x 1 root root 5953800 13 giu 21.32 /usr/local/lib/libSDL2-2.0.so.0.0.0
-rw-r--r-- 1 root root 7437724 13 giu 21.32 /usr/local/lib/libSDL2.a
lrwxrwxrwx 1 root root      26 13 giu 21.37 /usr/local/lib/libSDL2_image-2.0.so.0 -> libSDL2_image-2.0.so.0.0.0
-rwxr-xr-x 1 root root  472208 13 giu 21.37 /usr/local/lib/libSDL2_image-2.0.so.0.0.0
-rw-r--r-- 1 root root  539638 13 giu 21.37 /usr/local/lib/libSDL2_image.a
-rwxr-xr-x 1 root root     989 13 giu 21.37 /usr/local/lib/libSDL2_image.la
lrwxrwxrwx 1 root root      26 13 giu 21.37 /usr/local/lib/libSDL2_image.so -> libSDL2_image-2.0.so.0.0.0
-rwxr-xr-x 1 root root     958 13 giu 21.32 /usr/local/lib/libSDL2.la
-rw-r--r-- 1 root root    3348 13 giu 21.32 /usr/local/lib/libSDL2main.a
lrwxrwxrwx 1 root root      20 13 giu 21.32 /usr/local/lib/libSDL2.so -> libSDL2-2.0.so.0.0.0
-rw-r--r-- 1 root root  565370 13 giu 21.32 /usr/local/lib/libSDL2_test.a
lrwxrwxrwx 1 root root      25 13 giu 21.48 /usr/local/lib/libSDL2_ttf-2.0.so.0 -> libSDL2_ttf-2.0.so.0.14.1
-rwxr-xr-x 1 root root  145640 13 giu 21.48 /usr/local/lib/libSDL2_ttf-2.0.so.0.14.1
-rw-r--r-- 1 root root  132154 13 giu 21.48 /usr/local/lib/libSDL2_ttf.a
-rwxr-xr-x 1 root root     993 13 giu 21.48 /usr/local/lib/libSDL2_ttf.la
lrwxrwxrwx 1 root root      25 13 giu 21.48 /usr/local/lib/libSDL2_ttf.so -> libSDL2_ttf-2.0.so.0.14.1
```

**Comment by fgsfdsfgs** [comment]
It just seems like somehow your SDL2 libs are version 2.0.0 or 2.0.1, because it can't find **only** those functions, which were added in 2.0.1 and 2.0.4, yet it links all the other shit (e.g. most SDL_GameController functions, which were added in 2) just fine, so it obviously does pick up *something* for libSDL2. Maybe do a clean install of the `sdl2` package?

**Comment by GbaCretin** [comment]
> It just seems like somehow your SDL2 libs are version 2.0.0 or 2.0.1, because it can't find **only** those functions, which were added in 2.0.1 and 2.0.4, yet it links all the other shit (e.g. most SDL_GameController functions, which were added in 2) just fine, so it obviously does pick up _something_ for libSDL2. Maybe do a clean install of the `sdl2` package?

It works now, thanks!
