### ISSUE TITLE
Cannot compile on macos x

### ISSUE THREAD

**Issue by arivega** [sm64pc/sm64ex#442]
I have actually successfully compiled this before and saw there was a new update however after trying to do so it says that there's an error with aiff_extract_codebook.c 
![image](https://user-images.githubusercontent.com/38743888/97947512-5bcada80-1d42-11eb-960a-86bff16b7dcf.png) 
any fix for this?

**Comment by fgsfdsfgs** [comment]
Why is that building with -Werror? Is that a new thing in Clang, enabling such flags by default?
Either add ` -Wno-error` to the end of [this line](https://github.com/sm64pc/sm64ex/blob/master/tools/Makefile#L16) in `tools/Makefile`, or add `#include <stdio.h>` to the beginning of `tools/aiff_extract_codebook.c`, although I reckon there's gonna be more warnings down the line.
