### ISSUE TITLE
Controller horizontal analog camera control reverts to C-button style in all 3 Bowser stages

### ISSUE THREAD

**Issue by InsanityOnABun** [sm64pc/sm64ex#72]
Mouse camera control still works as expected if enabled, but horizontal analog control with a controller does not. Vertical still works fine.

Edit - happens in all 3 Bowser stages.

**Comment by Zero-Shift** [comment]
Confirmed this bug exists, but it happens on all 3 Bowser stages.

**Comment by FazanaJ** [comment]
Not a bug, this is by design. Bowser levels originally had an 8 directional camera, to make traversing them easier, and so does puppycam.
