### ISSUE TITLE
Invert axis options have the opposite effect on gamepad vs mouse

### ISSUE THREAD

**Issue by Reonu** [sm64pc/sm64ex#82]
**Describe the bug**
If you "invert" the axis on a gamepad, then the game will play with normal (non-inverted) camera controls. This is weird but whatever.

The thing is, when playing with a mouse it does work as it should: Enabling axis inversion means having inverted camera, and disabling it means having regular camera controls. This means that if you "invert" the axis in order to play with a gamepad with non-inverted camera controls, then mouse look will have inverted camera controls. 

Either the game should have separate settigns for gamepad and mouse, or this setting should act the same for both gamepad and mouse.

**To Reproduce**
Enable inverted on both X and Y axis
Use a gamepad. It has non-inverted camera controls.
Then use mouse look. It has inverted camera controls.

**Expected behavior**
Either both are inverted or both are not inverted.

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - Windows 10

**Smartphone (please complete the following information):**
**Additional context**

**Comment by coltongit** [comment]
Please check that PR #176 fixes this issue, and if it does for you, then it'll be ready to merge

**Comment by vrmiguel** [comment]
Fixed in #210
